---
title: "60 millions d'Européens ont traversé l'Atlantique"
date: "Août 2009"
---

L'ouvrage d'Hatton et Williamson (noté HW ci-après), dont je vais vous résumer quelques chapitres aujourd'hui, analyse l'Histoire des migrations internationales et ses conséquences économiques. Il est séparé en quatre parties relatant 1) la montée de l'immigration de masse durant le 19ème siècle (chapitre 2 à 7) 2) la chute des migrations internationales durant la première partie du 20ème (chapitre 8-9) 3) la montée d'une nouvelle immigration au lendemain de la seconde guerre mondiale (chapitre 10 à 15) 4) les migrations à venir (chapitre 16 à 18).

## Evolution des migrations internationales (Chapitres 2-3-4)

Les deux premiers chapitres opèrent un bref tour d'horizon de l'histoire des migrations de 1500 à 1900. Cette histoire semble avoir connu un tournant radical entre 1820 et 1850. En effet les premières migrations européennes vers le territoire américain étaient d'une ampleur relativement faible en comparaison avec l'incroyable explosion connue après 1820. Cette faiblesse s'explique bien évidemment par le coût élevé du voyage, d'après HW il fallait 5 mois de salaire pour un travailleur agricole du Sud de l'Angleterre en 1650 pour réaliser la traversée de l'Atlantique (il est à noter que ces travailleurs gagnaient l'un des salaires les plus élevé d'Europe). En raison de ce prix élevé les migrants étaient rares. Ainsi à partir de 1760-1820 le commerce d'esclave, hélas lucratif (selon Eltis (2002) un esclave coûtait 30$, le voyage 30$ de plus et il était finalement revendu 900$ à Cuba) représente une part prépondérante des migrations.

Mais à partir de 1830 le nombre d'Européens libres dépasse le nombre d'Africains déportés. La transition d'une migration forcée à une migration libre s'opère rapidement: la part des migrants libres était de 20% en 1820 et elle passe à 80% en 1840 (aux USA mais aussi en Australie). Au cours de ce 19ème siècle, les migrations connaissent une nouvelle évolution, les migrations libres de 1800 étaient composées de famille dont les membres étaient relativement riches, à l'inverse les migrants de la fin du siècle sont des urbains moins qualifiés et très jeunes. Mais au fait, d'où venaient-ils et où allaient-ils?

Les migrants proviennent, jusqu'aux environs de 1830, d'Angleterre et d'Allemagne, puis d'Europe du Nord (Scandinavie etc) et enfin à partir de 1880 d'Europe du Sud et de l'Est (Italie, Pologne etc). Jusqu'en 1880, les USA attirent la plus grande part des migrants, pour vous donner un ordre d'idée entre 1846 et 1850 les USA attirent 81% des migrations vers les amériques. La tendance s'infléchit cependant à partir de 1880, et profite à l'Argentine et au Brésil. Enfin à partir de 1900 le Canada attire de plus en plus de migrants (ceci dit le flux est tout juste positif tant l'émigration européenne vers le Canada est compensée par l'émigration canadienne vers les USA d'après McInnis (1994)).

Autre fait marquant, avec la chute des coûts de transport les retours migratoires deviennent importants, environ 30% des flux entre 1890 et 1914, certains pays comme l'Argentine ont même pu atteindre les 47% (retour des espagnols et des portugais).

Les coûts migratoires ayant diminué, la qualification des migrants semble avoir suivi, des migrants moins riches et moins qualifiés peuvent se payer le voyage. Ceci dit l'exemple irlandais d'O'Grada et O'Rourke (1997) invite à relativiser, les plus pauvres n'ont tout de même pas les moyens financiers pour migrer et vivent dans des conditions très difficiles notamment lors de la Famine de 1840. Revenons sur cette période qui est encore dans les mémoires irlandaises. Entre 1846 et 1850 les irlandais représentaient 71% des migrants européens et 50% de l'immigration américaine. L'Irlande qui avait connu une forte croissance démographique (pop de 4.8 millions en 1791 à 8.2 millions en 1841) se vide peu à peu (plus que 5.8 millions en 1850). Environ 1 million d'Irlandais étaient trop pauvres pour fuir et sont morts en Irlande.

Cette émigration a eu deux effets: 1) elle a facilité la création de réseaux 2) elle a élevé le salaire en Irlande. Ces deux éléments ont induit de [l'hystérèse](http://fr.wikipedia.org/wiki/Hyst%C3%A9r%C3%A9sis), la vague importante d'immigration Irlandaise dans les années 1890 s'explique sans doute par celle réalisée 50 ans plus tôt lors de la grande famine, en effet comme le note Geary:

> *"The great exodus of 1847-1854, in placing vast Irish population accross the Atlantic and the Irish sea which created a powerful magnetic field in which millions of Irish were irresistibly drawn from their native country in subsequent decades, was the fount and origin of Irish emigration and depopulation.... [The Famine made] migration part of the ordinary life of nearly every family in Ireland...thus making Irish labour the most mobile in the world and the most free to pursue its best market (Geary, 1935-1936, 25, 31)"*

**Les migrations présentes s'expliquent à la lumière de celles passées. L'Histoire économique compte** (pour un autre exemple déjà traité voir [ici](http://blogageco.blogspot.com/2009/06/aux-origines-du-sous-developpement-en.html)).

Evidemment, d'autres facteurs jouent pour expliquer les migrations, le premier auquel un économiste pense c'est le salaire. Les analyses de HW nous enseignent que les salaires ont fortement augmenté en Europe. Plus particulièrement au Danemark, en Suède, en Irlande, en Norvège et un peu moins en Belgique, France et Espagne. Si l'on croise ces informations avec les taux d'émigration la relation est "faiblement" négative. En d'autres termes, une hausse des salaires dans le pays d'origine ne semble pas avoir d'impact sur les départs. Ceci dit cette analyse est incomplète ce qui compte, ce n'est pas le salaire dans le pays d'origine mais le salaire relatif entre le pays d'accueil et d'origine. Dans une grande partie de la littérature théorique sur les migrations (notamment en économie géographique) ce salaire relatif est déterminant dans l'explication des flux migratoires. Or d'après les auteurs, la relation entre salaires relatif et migration n'est pas évidente. En fait les migrations ont suivi des cycles de croissance puis de décroissance et les salaires à eux seuls ne peuvent pas expliquer l'ensemble de ces observations.

D'après HW la **révolution industrielle** a eu trois effets importants 1) elle a engendré une hausse des salaires en Europe 2) elle a généré une baisse des coûts de transports 3) elle a engendré des taux de croissance important dans les pays d'accueil. Les nouveaux migrants ont ainsi pu s'enrichir et financer une partie du voyage de ceux qui étaient restés en Europe.

D'après les auteurs les points 1 et 2 pourraient expliquer les phases croissance puis de décroissance migratoires, dans un premier temps l'industrialisation permet de relâcher la contrainte financière liée aux coûts de déplacements puis à mesure que les pays européens s'enrichissent la nécessité d'émigrer devient moins importante. Cependant, le point 3, dénommé **effet réseaux** perturbe sans doute ce cycle. HW notent ainsi que parmi les émigrés une partie non négligeable voyageaient avec des tickets prépayés par des agents du pays d'accueil. Ces effets réseaux en jouant sur les coûts de déplacement et d'installation des migrants (facilité pour trouver un emploi, logement temporaire etc) ont eu un effet certain.

## Situation des migrants (chapitre 5)

A la fin du 18ème, début 19ème, les migrants étaient plutôt jeunes, ce qui n'est pas étonnant du point de vue des **choix inter-temporels**. Cette notion de temps peut sembler d'autant plus importante, que les gains des migrants ne sont pas immédiats et vont même en diminuant au fil du 19ème, en effet d'année en année les nouveaux migrants gagnent moins que les anciens (Hatton (2000)). D'après vous, cette baisse des rémunérations des migrants indique t-elle un déclin des qualifications des migrants? C'est justement la question posée à la commission Dillingham dans les années (1907-1911), et les conclusions de cette commission sont alors tranchées, elle oppose les premières vagues d'immigration composée d'anglais, d'irlandais, d'allemand et de scandinave à la nouvelle immigration composée d'Italiens et d'européens de l'Est qu'elle considère comme étant beaucoup moins qualifiés.

A juste titre, ce rapport a été fortement critiqué, d'après Hatton (2000) il faut reprendre cette analyse et distinguer deux éléments, d'un côté si l'on compare l'ancienne vague à la nouvelle, les émigrés de chaque pays sont sans doute plus qualifiés que leurs ancêtres (un français de 1900 était plus qualifié qu'un français de 1800 puisque ce dernier ne connaissait rien de la révolution industrielle), d'un autre côté une grande partie de la nouvelle vague provient des pays les moins industrialisés, c'est le "**source country composition effect**". Il faut donc déterminer l'effet dominant, selon les calculs d'Hatton (2000), c'est le composition effect qui domine, mais il est cependant décroissant et sa dominance est faible. Hatton (2000) note ainsi que la part des travailleurs qualifiés dans la population migrante a diminué de 4.3 % entre 1873 et 1913. Ceci dit si l'effet composition était resté constant cette part aurait augmenté de 6%.

Mais cette question n'est pas vraiment la plus intéressante, les auteurs poussent un peu loin l'analyse en réalisant l'étude suivante: si on fait le calcul sur tout le cycle de vie quels ont été les gains d'un migrant et quels auraient été ses gains s'il n'avait pas migré. **Ils observent alors que les migrants gagnent 50% de plus que s'ils étaient restés dans leur pays d'origine**. Ce résultat est évidemment discutable, pour réaliser ce calcul, on regarde par exemple le salaire de Mr A, boulanger de son état qui a migré de France vers les USA et on le compare au salaire de Mr B qui est resté en France. Or Mr A n'est pas Mr B, peut être que A aurait gagné un salaire supérieur à B même s'il était resté en France, tout simplement parce qu'il fait du meilleur pain, qu'il est plus commerçant etc.... Ce problème de variables inobservables est aussi rencontré lorsque les auteurs abordent la question de la fuite des travailleurs qualifiés européens et ses conséquences pour l'Europe. En se basant sur des données observables (analphabétisme par ex), les auteurs concluent que la fuite des ouvriers qualifiés européens (notamment observée dans les années 1830, ensuite on l'a vu, le niveau de qualification baisse) vers les amériques a été d'une faible ampleur. Ils notent cependant que leur analyse en sous-estime la mesure, il est possible que ce soient les données non observables qui comptent (esprit entrepreneurial par exemple).

Les auteurs abordent ensuite les liens entre migrations et situations des natifs. Comment les migrations affectent-elles les emplois et les salaires des natifs. Sur le court terme peu d'impact, l'immigration est une variable d'ajustement, elle augmente en période de surchauffe et elle diminue en période de récession. Ainsi pendant la récession des années 1890 les retours aux pays sont plus nombreux, l'Amérique exporte son chômage. Sur le long terme cependant on s'attend à ce que soient les salaires qui jouent la variable d'ajustement. En effet l'augmentation des travailleurs peu qualifiés devrait se répercuter sur les salaires. La commission Dillingham défendait cette vision, mais ceci est cependant difficile à prouver empiriquement tant ce raisonnement est basé sur du "toute chose étant égale par ailleurs". Dans les faits, il est difficile de distinguer l'effet des migrations sur les salaires de tous les autres effets (choc technologique etc...) de plus les choix migratoires dépendent eux même des salaires .... Une bonne méthode est de regarder ces effets à une échelle géographique fine et de comparer les résultats sur tout le territoire. Ce genre d'étude est hélas trop rare. Goldin (1994) est une exception, en analysant plusieurs villes sur la période 1890-1915 elle montre qu'une augmentation de 1% du ratio migrants/natifs entraîne une baisse du salaire des peu qualifiés de 1 à 1.5%. Il semble donc que sur cette période, une hausse de l'immigration a diminué les salaires. Ceci dit ce genre d'analyse néglige le fait que lorsque les migrants se concentrent en un lieu, les natifs fuient vers un autre, donc la baisse des salaires n'est peut être qu'artificielle, c'est à dire due au fait que les salariés les plus aisés ont simplement déménagé (Schelling).

## En guise de conclusion

Dans quelques temps, un nouveau post sur les chapitres 6-9 qui montrent que les migrations ont permis une convergence importante des économies - l'ouverture des frontières aux migrants des pays pauvres semble être une aide au développement efficace - mais cela n'est pas sans conséquence sur le marché du travail du pays d'accueil. Ces conséquences, négatives mais souvent exagérées, rendent la politique migratoire endogène, c'est du moins l'histoire des Etats-Unis d'Amérique présentée par HW qui montrent qu'après une ouverture totale des frontières (60 millions d'européens ont traversé l'Atlantique durant le 19ème, à titre de comparaison en 1820, il n'y avait qu'un milliard d'être humain), le vote des natifs s'oriente vers une politique protectionniste à l'égard des migrants. Dans les années 1920-30, la mise en place des quotas migratoires marquent la fin des migrations internationales de masse.

Biblio: Hatton et Williamson, 2005, Global Migration and the World Economy. MIT press.
